#!/usr/bin/env bash
# Install git hooks that keep .cursor/ and .claude/ in sync with src/.
#
# Hooks installed:
#   post-merge     — runs after `git pull` / `git merge`
#   post-checkout  — runs after branch switch / fresh clone checkout
#
# Idempotent. Safe to re-run.

set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

hooks_dir="$(git rev-parse --git-path hooks)"
mkdir -p -- "$hooks_dir"

install_hook() {
  local name="$1"
  local path="$hooks_dir/$name"
  cat > "$path" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — regenerates vendor dirs after
# branch/merge changes so .cursor/ and .claude/ reflect the latest src/.
set -e
repo_root="$(git rev-parse --show-toplevel)"
if [[ -x "$repo_root/scripts/sync-vendor-dirs.sh" ]]; then
  bash "$repo_root/scripts/sync-vendor-dirs.sh" >/dev/null
fi
HOOK
  chmod +x "$path"
  echo "installed: $path"
}

install_hook post-merge
install_hook post-checkout

echo "done. Run 'bash scripts/sync-vendor-dirs.sh' once to bootstrap."
